#!/bin/bash

# The production directory
WORKDIR="/home/pi/televerket-python"

# The Git repo
GIT="/home/pi/televerket-python.git"

# Deploy the content
git --work-tree=$WORKDIR --git-dir=$GIT checkout -f
export GIT_REV=`git --git-dir=$GIT rev-parse --short HEAD`

# Do stuff like starting the project
cd $WORKDIR || exit
